const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];
const LS={get(k,f=null){try{return JSON.parse(localStorage.getItem(k))??f}catch{return f}},set(k,v){localStorage.setItem(k,JSON.stringify(v))},del(k){localStorage.removeItem(k)}};
const state={mood:null,intent:null,stress:50,energy:50};
const pageTitles={home:'いまの自分を、ちょっと整える。',care:'静かに戻る。',release:'安全に外へ出す。',think:'頭の中を整理する。',rest:'休むことを選ぶ。',record:'自分の傾向を見つける。',guide:'自分の取扱説明書。',safe:'今は、選択肢を減らす。'};
function go(page){$$('.page').forEach(p=>p.classList.toggle('active',p.dataset.page===page));$$('.bottom-nav [data-nav]').forEach(b=>b.classList.toggle('active',b.dataset.nav===page));$('#pageTitle').textContent=pageTitles[page]||pageTitles.home;location.hash=page==='home'?'':page;scrollTo({top:0,behavior:'smooth'})}
$$('[data-nav]').forEach(b=>b.addEventListener('click',()=>go(b.dataset.nav)));window.addEventListener('hashchange',()=>go(location.hash.replace('#','')||'home'));
$('#quickExit').addEventListener('click',()=>{stopVoiceMeter();document.body.innerHTML='<main style="font-family:system-ui;padding:30px;max-width:680px;margin:auto"><h1>メモ</h1><p>ページを閉じるか、戻るボタンで戻れます。</p></main>';document.title='メモ'});
$$('#moodGrid button').forEach(b=>b.addEventListener('click',()=>{state.mood=b.dataset.mood;$$('#moodGrid button').forEach(x=>x.classList.toggle('selected',x===b))}));
$$('#intentGrid button').forEach(b=>b.addEventListener('click',()=>{state.intent=b.dataset.intent;$$('#intentGrid button').forEach(x=>x.classList.toggle('selected',x===b))}));
$('#stressRange').addEventListener('input',e=>{state.stress=+e.target.value;$('#stressValue').textContent=e.target.value});$('#energyRange').addEventListener('input',e=>{state.energy=+e.target.value;$('#energyValue').textContent=e.target.value});
function route(){const{mood,intent,stress,energy}=state;let target='care',title='60秒RESET',reason='最初に短く落ち着くルートを出してるよ。';if(intent==='rest'||energy<25){target='rest';title='NOTHING MODE';reason='エネルギーが低めなので、考える機能より休息を上に出してる。'}else if(intent==='release'||mood==='angry'){target='release';title='RELEASE → COOL DOWN';reason='発散したい気持ちを安全に外へ出してから、クールダウンにつなぐ。';$('#releaseBefore').value=stress;$('#releaseBeforeValue').textContent=stress}else if(intent==='think'&&energy>=30){target='think';title='BRAIN DUMP';reason='整理したいと選んだので、まず頭の中を外に出すルート。'}else if(stress>=80){target='care';title='GROUNDING';reason='ストレスが高めなので、長い分析より短いGroundingを優先。'}else if(mood==='tired'){target='rest';title='5分REST';reason='疲れを選んだので、まず休むルート。'}$('#recommendationCard').classList.remove('hidden');$('#recommendationTitle').textContent=title;$('#recommendationReason').textContent=reason;$('#recommendationOpen').dataset.target=target}
$('#routeButton').addEventListener('click',route);$('#recommendationOpen').addEventListener('click',e=>go(e.currentTarget.dataset.target||'care'));$('#skipToday').addEventListener('click',()=>alert('今日は記録なしでOK。'));

let breathInterval=null,breathCountdown=null,breathLeft=60,breathPhase=0;const phases=[['吸う','inhale',4],['止める','',2],['吐く','exhale',6]];
function setBreathPhase(){const[label,cls]=phases[breathPhase%phases.length];$('#breathText').textContent=label;$('#breathOrb').classList.remove('inhale','exhale');if(cls)$('#breathOrb').classList.add(cls);breathPhase++}
function stopBreath(){clearInterval(breathInterval);clearInterval(breathCountdown);breathInterval=breathCountdown=null;breathLeft=60;$('#breathOrb').classList.remove('inhale','exhale');$('#breathText').textContent='スタート';$('#breathTimer').textContent='01:00'}
$('#startBreathing').addEventListener('click',()=>{stopBreath();breathLeft=60;breathPhase=0;setBreathPhase();let phaseSeconds=phases[0][2],phaseIndex=0;breathInterval=setInterval(()=>{phaseSeconds--;if(phaseSeconds<=0){phaseIndex=(phaseIndex+1)%phases.length;breathPhase=phaseIndex;setBreathPhase();phaseSeconds=phases[phaseIndex][2]}},1000);breathCountdown=setInterval(()=>{breathLeft--;$('#breathTimer').textContent=`00:${String(Math.max(0,breathLeft)).padStart(2,'0')}`;if(breathLeft<=0){stopBreath();$('#breathText').textContent='おつかれさま'}},1000)});$('#stopBreathing').addEventListener('click',stopBreath);
const groundSteps=['見えるものを1つ、ゆっくり探してみて。','触れている感覚を1つ確かめてみて。','聞こえる音を1つ探してみて。','肩の力を少しだけ抜いてみて。','今いる場所と、今日の日付を頭の中で確認して終わり。'];let groundIndex=0;$('#nextGround').addEventListener('click',()=>{groundIndex=(groundIndex+1)%groundSteps.length;$('#groundStep').textContent=groundSteps[groundIndex]});

const releaseState={before:50,started:false,used:new Set(),rhythmCount:0,shakeRemaining:12};
function markTool(name){releaseState.used.add(name);const card=$(`.release-tool[data-tool="${name}"]`);if(card)card.classList.add('done');renderUsedTools()}
function renderUsedTools(){const names={scribble:'落書き',rhythm:'リズム',word:'言葉を流す',shake:'Shake Away',paper:'紙を捨てる',voice:'声量メーター',move:'Movement'};const used=[...releaseState.used].map(k=>names[k]||k);$('#usedTools').textContent=used.length?`使ったもの：${used.join(' / ')}`:'まだ使った機能はないよ。'}
$('#releaseBefore').addEventListener('input',e=>$('#releaseBeforeValue').textContent=e.target.value);$('#releaseAfter').addEventListener('input',e=>$('#releaseAfterValue').textContent=e.target.value);
$('#startReleaseSession').addEventListener('click',()=>{releaseState.before=+$('#releaseBefore').value;releaseState.started=true;$('#releaseAfter').value=releaseState.before;$('#releaseAfterValue').textContent=releaseState.before;$('#releaseSessionStatus').textContent=`開始値 ${releaseState.before}。好きな機能を1つ選んでOK。`;$('#startReleaseSession').textContent='開始済み'});

const canvas=$('#scribbleCanvas'),ctx=canvas.getContext('2d');let drawing=false,last=null,drawn=false;
function pos(e){const r=canvas.getBoundingClientRect(),t=e.touches?.[0]||e;return{x:(t.clientX-r.left)*(canvas.width/r.width),y:(t.clientY-r.top)*(canvas.height/r.height)}}
function startDraw(e){drawing=true;last=pos(e);e.preventDefault()}function draw(e){if(!drawing)return;const p=pos(e);e.preventDefault();const speed=Math.hypot(p.x-last.x,p.y-last.y);ctx.strokeStyle='#355b67';ctx.lineCap='round';ctx.lineWidth=Math.max(4,Math.min(24,speed*.25));ctx.beginPath();ctx.moveTo(last.x,last.y);ctx.lineTo(p.x,p.y);ctx.stroke();last=p;drawn=true}function endDraw(){drawing=false}
['mousedown','touchstart'].forEach(ev=>canvas.addEventListener(ev,startDraw,{passive:false}));['mousemove','touchmove'].forEach(ev=>canvas.addEventListener(ev,draw,{passive:false}));['mouseup','mouseleave','touchend'].forEach(ev=>canvas.addEventListener(ev,endDraw));$('#clearCanvas').addEventListener('click',()=>{ctx.clearRect(0,0,canvas.width,canvas.height);drawn=false});$('#markScribbleDone').addEventListener('click',()=>{if(drawn)markTool('scribble');$('#cooldownGate').scrollIntoView({behavior:'smooth',block:'start'})});

let audioCtx=null;function ac(){if(!audioCtx)audioCtx=new(window.AudioContext||window.webkitAudioContext)();if(audioCtx.state==='suspended')audioCtx.resume();return audioCtx}
function noiseBuffer(c,d=.18){const len=Math.floor(c.sampleRate*d),buf=c.createBuffer(1,len,c.sampleRate),data=buf.getChannelData(0);for(let i=0;i<len;i++)data[i]=Math.random()*2-1;return buf}
function drum(type){const c=ac(),now=c.currentTime,g=c.createGain();g.connect(c.destination);if(type==='kick'){const o=c.createOscillator();o.type='sine';o.frequency.setValueAtTime(150,now);o.frequency.exponentialRampToValueAtTime(48,now+.18);g.gain.setValueAtTime(.8,now);g.gain.exponentialRampToValueAtTime(.001,now+.22);o.connect(g);o.start(now);o.stop(now+.23)}else if(type==='tom'){const o=c.createOscillator();o.type='triangle';o.frequency.setValueAtTime(180,now);o.frequency.exponentialRampToValueAtTime(95,now+.18);g.gain.setValueAtTime(.55,now);g.gain.exponentialRampToValueAtTime(.001,now+.25);o.connect(g);o.start(now);o.stop(now+.26)}else{const n=c.createBufferSource();n.buffer=noiseBuffer(c,type==='clap'?.12:.18);const f=c.createBiquadFilter();f.type='highpass';f.frequency.value=type==='clap'?1100:800;n.connect(f);f.connect(g);g.gain.setValueAtTime(type==='clap'?.35:.45,now);g.gain.exponentialRampToValueAtTime(.001,now+(type==='clap'?.13:.2));n.start(now);n.stop(now+.22);if(type==='snare'){const o=c.createOscillator(),og=c.createGain();o.type='triangle';o.frequency.value=165;og.gain.setValueAtTime(.2,now);og.gain.exponentialRampToValueAtTime(.001,now+.12);o.connect(og);og.connect(c.destination);o.start(now);o.stop(now+.13)}}}
$$('#rhythmPads button').forEach(b=>b.addEventListener('pointerdown',()=>{drum(b.dataset.drum);releaseState.rhythmCount++;$('#rhythmCount').textContent=releaseState.rhythmCount;b.classList.add('hit');setTimeout(()=>b.classList.remove('hit'),100);if(releaseState.rhythmCount>=4)markTool('rhythm')}));$('#finishRhythm').addEventListener('click',()=>{if(releaseState.rhythmCount)markTool('rhythm');$('#cooldownGate').scrollIntoView({behavior:'smooth'})});

$('#burnWords').addEventListener('click',()=>{const v=$('#releaseText').value.trim();if(!v)return;const chip=document.createElement('div');chip.className='word-chip';chip.textContent=v.slice(0,120);$('#wordStage').innerHTML='';$('#wordStage').appendChild(chip);$('#releaseText').value='';markTool('word');setTimeout(()=>$('#wordStage').innerHTML='',1200)});

function renderShakeDots(){const box=$('#shakeClouds');box.innerHTML='';for(let i=0;i<releaseState.shakeRemaining;i++){const d=document.createElement('i');d.className='shake-dot';d.style.left=`${8+(i*37)%82}%`;d.style.top=`${8+(i*23)%70}%`;d.style.animationDelay=`${(i%5)*.25}s`;box.appendChild(d)}$('#shakeCount').textContent=releaseState.shakeRemaining}
function popShake(){if(releaseState.shakeRemaining<=0)return;const dots=$$('#shakeClouds .shake-dot'),d=dots[dots.length-1];if(d)d.classList.add('gone');releaseState.shakeRemaining--;$('#shakeCount').textContent=releaseState.shakeRemaining;if(releaseState.shakeRemaining===0){markTool('shake');$('#shakeStatus').textContent='全部消えた。ここで終わってOK。'}}
let lastShake=0;function motionHandler(e){const a=e.accelerationIncludingGravity||e.acceleration;if(!a)return;const mag=Math.sqrt((a.x||0)**2+(a.y||0)**2+(a.z||0)**2),now=Date.now();if(mag>20&&now-lastShake>350){lastShake=now;popShake()}}
$('#enableShake').addEventListener('click',async()=>{try{if(typeof DeviceMotionEvent!=='undefined'&&typeof DeviceMotionEvent.requestPermission==='function'){const p=await DeviceMotionEvent.requestPermission();if(p!=='granted')throw new Error('denied')}if('DeviceMotionEvent'in window){window.addEventListener('devicemotion',motionHandler);$('#shakeStatus').textContent='センサーON。軽く振ってみて。';$('#enableShake').textContent='センサーON'}else $('#shakeStatus').textContent='この端末ではセンサーを使えないみたい。タップ版を使ってね。'}catch{$('#shakeStatus').textContent='センサー許可がないので、タップ版を使えるよ。'}});$('#manualShake').addEventListener('click',popShake);renderShakeDots();

$('#paperText').addEventListener('input',e=>$('#paperSheet').textContent=e.target.value||'ここに紙が出るよ');$('#crumplePaper').addEventListener('click',()=>{const v=$('#paperText').value.trim();if(!v)return;const sheet=$('#paperSheet');sheet.classList.add('crumpling');markTool('paper');setTimeout(()=>{sheet.classList.remove('crumpling');$('#paperText').value='';sheet.textContent='捨てたよ。次を書いてもいいし、終わってもいい。'},720)});

let micStream=null,analyser=null,voiceRAF=null,voiceCtx=null;
async function startVoiceMeter(){try{if(!navigator.mediaDevices?.getUserMedia)throw new Error('unsupported');stopVoiceMeter();micStream=await navigator.mediaDevices.getUserMedia({audio:{echoCancellation:true,noiseSuppression:true},video:false});voiceCtx=new(window.AudioContext||window.webkitAudioContext)();const src=voiceCtx.createMediaStreamSource(micStream);analyser=voiceCtx.createAnalyser();analyser.fftSize=512;src.connect(analyser);const data=new Uint8Array(analyser.fftSize);const tick=()=>{analyser.getByteTimeDomainData(data);let sum=0;for(const x of data){const n=(x-128)/128;sum+=n*n}const rms=Math.sqrt(sum/data.length),pct=Math.min(100,Math.round(rms*360));$('#voiceLevel').style.width=pct+'%';$('#voicePercent').textContent=pct+'%';if(pct>12)markTool('voice');voiceRAF=requestAnimationFrame(tick)};tick();$('#voiceStatus').textContent='マイクON。音声データは録音・保存していないよ。'}catch{$('#voiceStatus').textContent='マイクを使えなかったよ。許可設定かHTTPS接続を確認してね。'}}
function stopVoiceMeter(){if(voiceRAF)cancelAnimationFrame(voiceRAF);voiceRAF=null;if(micStream)micStream.getTracks().forEach(t=>t.stop());micStream=null;if(voiceCtx){voiceCtx.close().catch(()=>{});voiceCtx=null}if($('#voiceLevel'))$('#voiceLevel').style.width='0%';if($('#voicePercent'))$('#voicePercent').textContent='0%';if($('#voiceStatus'))$('#voiceStatus').textContent='停止中。録音データは残らないよ。'}
$('#startVoice').addEventListener('click',startVoiceMeter);$('#stopVoice').addEventListener('click',stopVoiceMeter);

let moveInterval=null,moveLeft=30;const moveSteps=[{until:20,text:'肩を少し上げて、ストンと落とす'},{until:10,text:'腕と手を軽くブラブラする'},{until:0,text:'肩をゆるめて、ゆっくり息を吐く'}];
function stopMovement(reset=true){clearInterval(moveInterval);moveInterval=null;if(reset){moveLeft=30;$('#movementTimer').textContent='00:30';$('#movementProgress').style.width='0%';$('#movementStep').textContent=moveSteps[0].text}}
$('#startMovement').addEventListener('click',()=>{stopMovement();moveLeft=30;moveInterval=setInterval(()=>{moveLeft--;$('#movementTimer').textContent=`00:${String(Math.max(0,moveLeft)).padStart(2,'0')}`;$('#movementProgress').style.width=`${((30-moveLeft)/30)*100}%`;const step=moveSteps.find(s=>moveLeft>s.until)||moveSteps[2];$('#movementStep').textContent=step.text;if(moveLeft<=0){clearInterval(moveInterval);moveInterval=null;$('#movementStep').textContent='ここまで。力を抜いて終わり。';markTool('move')}},1000)});$('#stopMovement').addEventListener('click',()=>stopMovement(true));

function escapeHtml(s){return String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
function renderReleaseHistory(){const arr=LS.get('releaseHistory',[]).slice(-5).reverse();$('#releaseHistory').innerHTML=arr.length?arr.map(r=>{const d=r.after-r.before,sign=d>0?`+${d}`:`${d}`,tools=(r.tools||[]).join(' / ')||'—';return `<div class="record-item"><strong>${escapeHtml(r.date)}</strong>　${r.before} → ${r.after}（${sign}）<br><span class="muted">${escapeHtml(tools)}</span></div>`}).join(''):'<p class="muted small">まだ前後記録はないよ。</p>'}
$('#compareRelease').addEventListener('click',()=>{if(!releaseState.started){releaseState.before=+$('#releaseBefore').value;releaseState.started=true}const after=+$('#releaseAfter').value,delta=after-releaseState.before,box=$('#releaseResult');box.classList.remove('hidden','up');if(delta>0)box.classList.add('up');$('#releaseDelta').textContent=delta===0?'±0':delta>0?`+${delta}`:`${delta}`;$('#releaseResultText').textContent=delta<0?'少し下がったみたい。まだ必要ならRESETかRESTへ。':delta===0?'変わらない日もあるよ。別の方法に変えてOK。':'今は上がってるみたい。発散を続けず、RESETかRESTに切り替えよう。';$('#cooldownActions').classList.remove('hidden');const names={scribble:'落書き',rhythm:'リズム',word:'言葉',shake:'Shake',paper:'Paper',voice:'声量',move:'Movement'},hist=LS.get('releaseHistory',[]);hist.push({date:new Date().toLocaleString('ja-JP',{month:'numeric',day:'numeric',hour:'2-digit',minute:'2-digit'}),before:releaseState.before,after,tools:[...releaseState.used].map(k=>names[k]||k)});LS.set('releaseHistory',hist.slice(-30));renderReleaseHistory()});$('#cooldownReset').addEventListener('click',()=>go('care'));$('#cooldownRest').addEventListener('click',()=>go('rest'));$('#finishReleaseSession').addEventListener('click',()=>{stopVoiceMeter();go('home')});

$('#brainDump').value=LS.get('brainDump','');$('#saveDump').addEventListener('click',()=>{LS.set('brainDump',$('#brainDump').value);alert('この端末に保存したよ。')});$('#deleteDump').addEventListener('click',()=>{LS.del('brainDump');$('#brainDump').value=''});
function renderWorries(){const arr=LS.get('worries',[]);$('#worryList').innerHTML=arr.map((w,i)=>`<li><span>${escapeHtml(w)}</span><button data-worry="${i}">捨てる</button></li>`).join('');$$('[data-worry]').forEach(b=>b.onclick=()=>{const a=LS.get('worries',[]);a.splice(+b.dataset.worry,1);LS.set('worries',a);renderWorries()})}
$('#addWorry').addEventListener('click',()=>{const v=$('#worryInput').value.trim();if(!v)return;const a=LS.get('worries',[]);a.push(v);LS.set('worries',a);$('#worryInput').value='';renderWorries()});$$('[data-control]').forEach(b=>b.addEventListener('click',()=>$('#controlResult').textContent=`「${b.dataset.control}」に置いたよ。`));
let restInterval=null;$$('.rest-start').forEach(b=>b.addEventListener('click',()=>{clearInterval(restInterval);const mins=+b.dataset.min;if(!mins){$('#restTimer').textContent='時間を決めずに休んでOK。';return}let sec=mins*60;const tick=()=>{$('#restTimer').textContent=`${String(Math.floor(sec/60)).padStart(2,'0')}:${String(sec%60).padStart(2,'0')}`;if(sec--<=0){clearInterval(restInterval);$('#restTimer').textContent='もう少し休んでも、戻ってもいい。'}};tick();restInterval=setInterval(tick,1000)}));
function renderRecords(){const arr=LS.get('records',[]).slice(-7).reverse();$('#recordList').innerHTML=arr.length?arr.map(r=>`<div class="record-item"><strong>${r.date}</strong><br>${r.mood} ・ ストレス ${r.stress} ・ エネルギー ${r.energy}</div>`).join(''):'<p class="muted small">まだ記録はないよ。</p>'}
$('#saveRecord').addEventListener('click',()=>{const arr=LS.get('records',[]);arr.push({date:new Date().toLocaleDateString('ja-JP'),mood:$('#recordMood').selectedOptions[0].text,stress:+$('#recordStress').value,energy:+$('#recordEnergy').value});LS.set('records',arr.slice(-180));renderRecords();alert('保存したよ。')});
const manualKeys=['manualSigns','manualCare','manualAvoid','manualPeople'];manualKeys.forEach(k=>$('#'+k).value=LS.get(k,''));$('#saveManual').addEventListener('click',()=>{manualKeys.forEach(k=>LS.set(k,$('#'+k).value));alert('この端末に保存したよ。')});$('#showSafe').addEventListener('click',()=>go('safe'));$('#showPeople').addEventListener('click',()=>{const p=LS.get('manualPeople','').trim();$('#peopleBox').textContent=p||'MY GUIDEで「頼れる人」を登録しておくと、ここですぐ確認できるよ。';$('#peopleBox').classList.remove('hidden')});$('#supportInfo').addEventListener('click',()=>alert('公開版では、利用地域に合わせた公的な相談窓口ページへのリンクをここに設定する予定です。'));
renderWorries();renderRecords();renderReleaseHistory();go(location.hash.replace('#','')||'home');if('serviceWorker'in navigator){window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(()=>{}))}